# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WendyLabs.Wendy
PackageVersion: 2026.09.28-142251
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.28-142251/wendy-cli-windows-amd64-2026.09.28-142251.msi
  InstallerSha256: B2B2538392CC12C24A8A5087D2C708E541BA6ACA9C12C9554F5AE9232F2BCAFC
  ProductCode: '{DF8DD751-F799-40FF-88B5-D8AF6BC9C9A2}'
- Architecture: arm64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.28-142251/wendy-cli-windows-arm64-2026.09.28-142251.msi
  InstallerSha256: 2B275CAE47C2930B24C182C30B1A4FAACAC8A3A9DA7EA9192218CE5A4A7D1FA8
  ProductCode: '{6A9E3FFD-B3E1-46B7-B083-A93FF7B2B2A8}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
