# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WendyLabs.Wendy
PackageVersion: 2026.09.30-213433
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.30-213433/wendy-cli-windows-amd64-2026.09.30-213433.msi
  InstallerSha256: 158CEDA9F2588A404BBD3A318E08A8FB47AA1A2734BB5BB14FBE59D348CD178B
  ProductCode: '{4DC336AF-E46C-4EF1-9478-C42A6A42C40A}'
- Architecture: arm64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.30-213433/wendy-cli-windows-arm64-2026.09.30-213433.msi
  InstallerSha256: 9BC322C79BE1F59F2A560830DA6DB3970B24F6DFC1A66390331313D489FAD4F0
  ProductCode: '{2505B538-4170-4568-8F48-F3C5CC71D7E5}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
