# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WendyLabs.Wendy
PackageVersion: 2026.09.27-215032
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.27-215032/wendy-cli-windows-amd64-2026.09.27-215032.msi
  InstallerSha256: DC90CF3E056218BA6FB4DAC509D693E2B61BA4211193391F7E3F4B61492E61CB
  ProductCode: '{744EE944-487F-4B77-96B8-03E817878851}'
- Architecture: arm64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.09.27-215032/wendy-cli-windows-arm64-2026.09.27-215032.msi
  InstallerSha256: BB4B35FD5BBF30BCFA2E66E8678D09B8C425165CC9E7054E67E28835E84A6536
  ProductCode: '{10D79437-EF03-4806-BF46-C4F212BBD782}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
