# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WendyLabs.Wendy
PackageVersion: 2026.10.01-013419
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.10.01-013419/wendy-cli-windows-amd64-2026.10.01-013419.msi
  InstallerSha256: 634AE13A7CF3AD5DC6A500CADB0004D7ECB562B2A82EF696C7A7DEE4C1510F83
  ProductCode: '{5AB262CF-4ADC-4B92-8680-861BCBA09C4A}'
- Architecture: arm64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.10.01-013419/wendy-cli-windows-arm64-2026.10.01-013419.msi
  InstallerSha256: 558232D15730BFA85F79FFF5E9B3327DF02A4E4FEA97B98E36BBBC570E9AFC43
  ProductCode: '{4039E09D-749D-42E4-8314-0811A11A49E6}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
