# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WendyLabs.Wendy
PackageVersion: 2026.10.05-134249
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.10.05-134249/wendy-cli-windows-amd64-2026.10.05-134249.msi
  InstallerSha256: 42897EB00E41CFDD0BBF21D039495CDAE6F0A95A958A15E56A02763A92607C96
  ProductCode: '{5911B885-D34C-4D4E-9FB1-E92B2EE30EAC}'
- Architecture: arm64
  InstallerUrl: https://github.com/wendylabsinc/wendy-agent/releases/download/2026.10.05-134249/wendy-cli-windows-arm64-2026.10.05-134249.msi
  InstallerSha256: 327382AC8E3EC2DD0BB324597EF5FF762C5E6DE66E7A015A0276EFAB5BBE464A
  ProductCode: '{D8E22097-411F-48B2-86D5-AD5033756035}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
